### ISSUE TITLE
點選 menu 跑錯位置

### ISSUE THREAD

**Issue by pamcy** [pamcy/Personal-Website#2]
除了 code 的連結正常外
about 和 contact 連到的位置都不對
@cscolabear 好奇怪 @@

**Comment by cscolabear** [comment]
剛找到問題了 



-- tl;dr -- 到時候直接用說的比較快 @@

現在有問題的程式...
如果使用者點擊了 #about....
$('#about').offset().top 他的意思是 #about 到容器頂端之間的距離 (不是捲軸頂端哦)

但如果現在位置已經在 #about , 然後使用者點擊了 #code, 
實際上移動的位置不能是 `$('#code').offset().top`
因為移動捲軸的方法叫做 `scrollTop` (從捲軸頂端移到指定位置)
所以要給的值，應該是 $('#about').offset().top + 現在捲軸位置

**Comment by chinyi3005** [comment]
這是天書嗎，明明寫的都是中文，好像繞口令
