### ISSUE TITLE
使用 .menu 判斷使用者裝置的時機

### ISSUE THREAD

**Issue by cscolabear** [pamcy/Personal-Website#4]
這裡
[main.js L28](https://github.com/chinyi3005/Personal-Website/blob/master/assets/js/main.js#L28)
這樣做不太好，因為只會執行一次
如果使用者把畫面拉大拉小，`menuPosition` 的值不會改變哦

這樣比較好 :open_mouth: 
```
var isMobile = false;

function isMobileDevice() {
   var menuPosition = $('.menu').css('position');
    isMobile = false;

    if (menuPosition === 'fixed') {
        isMobile = true;
    }
}
```

這麼一來~
每次在呼叫 `isMobileDevice()` 的時候都會重新取得 `$('.menu').css('position')`

**Comment by pamcy** [comment]
了解，收到！
